### PR TITLE
FIX: [droid;x86] remove options not supported by clang

### PR DESCRIPTION
**Pull request by koying**
As discussed on slack.
Allows the addon to be built on android x86 now that we switched to clang

### CODE REVIEW

**Comment by wsnipex** [comment]
imho we can apply this patch for all platforms, so just placing the patch in the common dir should suffice

**Comment by koying** [comment]
Sure? I didn't want to impact linux x86, here.
The option might actually have a purpose...

**Comment by AlwinEsch** [comment]
It seems only be a performance issue there, for disc rip not related. Also was after test the sound OK :smile: 
See http://www.spec.org/cpu2006/flags/ic91_fp.html#user_F-mno-ieee-fp

But the current versions of  use vorbis and ogg already have CMakeLists.txt inside and the configure no more needed.

See https://github.com/xbmc/audioencoder.vorbis/pull/28
Can you confirm the compile and work on Android x86?

**Comment by AlwinEsch** [comment]
Not sure if this request still needed, as there comes now version 1.3.7 about.
Also does my Linux again makes problems about Java and the SDK of Android. Ubuntu have v11, where also needed by few parts in my system, but Android SDK still need v8 or v9 :unamused:. So I can not quickly test about.

Can someone, where have currently a working Android SDK and time, the build about X86/x86_64 on last released version?
Maybe this request can then closed.

**Comment by AlwinEsch** [comment]
@koying this request needed, otherwise becomes it closed!

**Pull request closed without merging**
