### PR TITLE
[win32] add windows specific dependencies

### PR DESCRIPTION
**Pull request by Montellese**
This adds the dependencies needed by win32. This is needed for xbmc/xbmc#6152 but can already be merged before as it doesn't hurt.

### CODE REVIEW

**Comment by Montellese** [comment]
@wsnipex @notspiff: Mind sanity checking the `CMakeLists.txt` files before I merge this?

**Comment by notspiff** [comment]
C language needs to be enabled

**Comment by wsnipex** [comment]
project() enables C and C++ by default. Why does he need to enable it specifically?

**Comment by notspiff** [comment]
That changed in 2.8 (or was it 2.6). And i keep forgetting. Nm the noise.

**Pull request merged**
